# Generated by Django 4.1.9 on 2023-05-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sofia_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profile_picture',
            field=models.TextField(default='/static/default_profile.png'),
        ),
    ]
