# Generated by Django 4.1.9 on 2023-05-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sofia_auth', '0002_useraccount_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
