# Generated by Django 4.1.9 on 2023-05-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('embedded_block', models.TextField()),
                ('movie_duration', models.TimeField()),
                ('country_short', models.CharField(max_length=2)),
                ('thumbnail', models.URLField()),
                ('status', models.BooleanField(default=True)),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
