# Generated by Django 4.1.9 on 2023-05-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sofia_movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='download_link',
            field=models.URLField(null=True),
        ),
    ]
