# Generated by Django 4.1.9 on 2023-05-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sofia_movie', '0002_movie_download_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='embedded_block',
        ),
        migrations.AddField(
            model_name='movie',
            name='embedded_link',
            field=models.URLField(null=True),
        ),
    ]
