# Generated by Django 4.1.9 on 2023-05-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sofia_movie', '0003_remove_movie_embedded_block_movie_embedded_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
